[package]
name = "unistate-ckb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ckb-fixed-hash-core = "0.116.1"
ckb-gen-types = "0.116.1"
ckb-jsonrpc-types = "0.116.1"
ckb-sdk = "3.2"
ckb-types = "0.116.1"
ckb-hash = "0.116.1"
hex = "0.4.3"
hex-literal = "0.4.1"
molecule = "0.8.0"
sea-orm = { version = "1.0.0-rc.5", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-bigdecimal"], default-features = false }
bigdecimal = "0.3"                                                                                                                                               # 为了 sea-orm 兼容性
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.38", features = ["serde"] }
sha3 = "0.10.8"
rayon = "1"
tracing = "0.1.40"
jsonrpsee = { version = "0.22", features = ["client", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing-subscriber = "0.3"
dotenvy = "0.15"
figment = { version = "0.10", features = ["env", "test", "toml"] }

[dev-dependencies]
criterion = "0.5.1"
rand = "0.9.0-alpha.1"

[[bench]]
name = "categorize"
harness = false
