[package]
name = "unistate-ckb"
version = "0.1.0"
edition = "2021"
authors = ["Cupnfish <cupnfish@icloud.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/unistate-io/unistate-ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ckb-fixed-hash-core = "0.116.1"
ckb-gen-types = "0.116.1"
ckb-jsonrpc-types = "0.116.1"
ckb-sdk = "3.2"
ckb-types = "0.116.1"
ckb-hash = "0.116.1"
hex = "0.4.3"
hex-literal = "0.4.1"
molecule = "0.8.0"
sea-orm = { version = "1.0.0-rc.7", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-bigdecimal"], default-features = false }
bigdecimal = "0.3"                                                                                                                                               # 为了 sea-orm 兼容性
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.38", features = ["serde"] }
sha3 = "0.10"
rayon = "1"
tracing = "0.1"
jsonrpsee = { version = "0.24", features = ["client", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing-subscriber = "0.3"
dotenvy = "0.15"
figment = { version = "0.10", features = ["env", "test", "toml"] }
async-scoped = { version = "0.9", features = ["use-tokio"] }
futures = "0.3"
dashmap = { version = "6.0", features = ["rayon"] }
const_field_count = "0.1"
pico-args = "0.5"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.9.0-alpha.1"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }

[[bench]]
name = "categorize"
harness = false
