[package]
name = "unistate-ckb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ckb-fixed-hash-core = "0.115.0-rc2"
ckb-gen-types = "0.115.0-rc2"
ckb-jsonrpc-types = "0.115.0-rc2"
ckb-sdk = "3.1.1"
ckb-types = "0.115.0-rc2"
hex = "0.4.3"
hex-literal = "0.4.1"
molecule = "0.8.0"
sea-orm = { version = "0.12", features = [ "sqlx-postgres","runtime-async-std-rustls", "macros" ] }
# tokio = { version = "1", features = ["full"] }
async-std = {version = "1",features = ["attributes"]}
chrono = { version = "0.4.38", features = ["serde"] }
