//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, const_field_count::FieldCount)]
#[sea_orm(table_name = "addresses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub address_id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub script_code_hash: Vec<u8>,
    pub script_hash_type: i16,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub script_args: Vec<u8>,
    pub first_seen_block_number: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub first_seen_tx_hash: Vec<u8>,
    pub first_seen_tx_timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
