//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, const_field_count::FieldCount)]
#[sea_orm(table_name = "clusters")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub id: Vec<u8>,
    pub cluster_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cluster_description: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub mutant_id: Option<Vec<u8>>,
    pub owner_address: Option<String>,
    pub is_burned: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub type_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::addresses::Entity",
        from = "Column::OwnerAddress",
        to = "super::addresses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Addresses2,
    #[sea_orm(
        belongs_to = "super::addresses::Entity",
        from = "Column::TypeId",
        to = "super::addresses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Addresses1,
    #[sea_orm(has_many = "super::spore_actions::Entity")]
    SporeActions,
    #[sea_orm(has_many = "super::spores::Entity")]
    Spores,
}

impl Related<super::spore_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SporeActions.def()
    }
}

impl Related<super::spores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
