//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, const_field_count::FieldCount)]
#[sea_orm(table_name = "rgbpp_locks")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub lock_args_hash: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tx_hash: Vec<u8>,
    pub output_index: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub lock_script_code_hash: Vec<u8>,
    pub lock_script_hash_type: i16,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub btc_txid: Vec<u8>,
    pub block_number: i64,
    pub tx_timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
