//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "spore_action_type")]
pub enum SporeActionType {
    #[sea_orm(string_value = "MintSpore")]
    MintSpore,
    #[sea_orm(string_value = "TransferSpore")]
    TransferSpore,
    #[sea_orm(string_value = "BurnSpore")]
    BurnSpore,
    #[sea_orm(string_value = "MintCluster")]
    MintCluster,
    #[sea_orm(string_value = "TransferCluster")]
    TransferCluster,
    #[sea_orm(string_value = "MintProxy")]
    MintProxy,
    #[sea_orm(string_value = "TransferProxy")]
    TransferProxy,
    #[sea_orm(string_value = "BurnProxy")]
    BurnProxy,
    #[sea_orm(string_value = "MintAgent")]
    MintAgent,
    #[sea_orm(string_value = "TransferAgent")]
    TransferAgent,
    #[sea_orm(string_value = "BurnAgent")]
    BurnAgent,
}
