//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use super::sea_orm_active_enums::SporeActionType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, const_field_count::FieldCount)]
#[sea_orm(table_name = "spore_actions")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub tx_hash: Vec<u8>,
    pub block_number: i64,
    pub action_type: SporeActionType,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub spore_id: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub cluster_id: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub proxy_id: Option<Vec<u8>>,
    pub from_address_id: Option<String>,
    pub to_address_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub action_data: Option<Json>,
    pub tx_timestamp: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub output_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
