on:
  release:
    types: [created]

name: Release Packaging

permissions:
  contents: write

jobs:
  release:
    name: Release Packaging
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: unistate-ckb

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Project
        run: cargo build --release

      - name: List Files in Target Directory
        run: ls -la target/release/

      - name: Create Tarball
        run: tar czf ${{ env.PACKAGE_NAME }}.tar.gz -C target/release ${{ env.PACKAGE_NAME }}

      - name: List Files in Current Directory
        run: ls -la

      - name: Check if Tarball Exists
        run: |
          if [ ! -f "${{ env.PACKAGE_NAME }}.tar.gz" ]; then
            echo "Tarball does not exist!"
            exit 1
          fi

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: ${{ env.PACKAGE_NAME }}.tar.gz
          file: ${{ env.PACKAGE_NAME }}.tar.gz
          tag: ${{ github.ref_name }}
          overwrite: true
